Repository project2025-a/project2025-next, pull requests merged in 2025-07, with the labels that each got.

#80 feat: Microsoft Clarity 스크립트 추가
  src/app/[locale]/layout.tsx
  src/types/env.d.ts
Labels: 🚀 배포, ✨기능 추가

#82 Microsoft Clarity 및 Hotjar 추적 코드 적용 + 쿼리 키 기본값 리팩토링
  src/app/[locale]/layout.tsx
  src/app/actions/keys.ts
  src/types/env.d.ts
Labels: 🚀 배포

#84 SSR Hydration 오류 및 QueryKey 구조 개선(간헐적 Fallback 대응)
  src/app/[locale]/(root)/log/[logId]/page.tsx
  src/app/actions/keys.ts
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/actions/user.ts
  src/app/api/log/route.ts
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/features/detail-log/LogBookmarkWithCount.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/detail-log/LogContentSection.tsx
  src/components/features/detail-log/LogDetailActions.tsx
  src/components/features/detail-log/PlaceBookmarkWithCount.tsx
  src/components/features/home/CarouselSection/Carousel.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/hooks/mutations/place/usePlaceBookmarkMutation.ts
  src/hooks/queries/log/useLog.ts
  src/lib/utils.ts
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#85 SSR 안정성 개선 & 검색 기능 확장 (log\_tag 포함)
  src/app/[locale]/(root)/log/[logId]/page.tsx
  src/app/actions/keys.ts
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/actions/user.ts
  src/app/api/log/route.ts
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/features/detail-log/LogBookmarkWithCount.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/detail-log/LogContentSection.tsx
  src/components/features/detail-log/LogDetailActions.tsx
  src/components/features/detail-log/PlaceBookmarkWithCount.tsx
  src/components/features/home/CarouselSection/Carousel.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/hooks/mutations/place/usePlaceBookmarkMutation.ts
  src/hooks/queries/log/useLog.ts
  src/lib/utils.ts
Labels: 🐞 버그 수정, 🚀 배포, 🛠️ 리팩토링, ✨기능 추가

#86 사용되지 않는 logId 변수 제거하여 ESLint 오류 해결
  src/hooks/mutations/place/usePlaceBookmarkMutation.ts
Labels: 🚀 배포

#90 지역 선택 태그 페이지 수정
  src/app/[locale]/(write)/register/log/page.tsx
  src/app/[locale]/(write)/register/tags/city/page.tsx
  src/app/[locale]/(write)/register/tags/country/page.tsx
  src/app/[locale]/(write)/register/tags/location/page.tsx
  src/app/[locale]/(write)/register/tags/mood/page.tsx
  src/app/[locale]/(write)/register/tags/sigungu/page.tsx
  src/components/common/Footer/RegisterFooter.tsx
  src/components/features/log/register/tags/SingleTagGroup.tsx
  src/constants/pathname.ts
Labels: 🛠️ 리팩토링

#94 Prisma 싱글톤 패턴 적용으로 커넥션 풀 초과 문제 해결
  prisma/prisma.ts
Labels: 🐞 버그 수정, 🚀 배포

#95 로그 등록,상세 페이지 UI 및 마이프로필 업로드 경로 수정
  src/components/features/profile/ProfileHeader/components/ProfileActionButton.tsx
Labels: 🐞 버그 수정, 🚀 배포, 🎨 디자인 / UI 작업

#97 홈 화면 장소 리스트 기능 구현 및 타입·상수 구조 정리
  src/app/[locale]/(root)/page.tsx
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/api/places/route.ts
  src/components/features/home/LatestPlaceContentSection/LatestPlaceContent.tsx
  src/components/features/home/LatestPlaceContentSection/LatestPlaceContentSection.tsx
  src/constants/fetchConfig.ts
  src/hooks/queries/place/usePlaces.ts
  src/hooks/queries/place/usePlacesBookmark.ts
  src/types/api/place.d.ts
Labels: ✨기능 추가

#98 홈 화면 장소 리스트 기능 구현 및 UI/구조 리팩토링
  src/app/[locale]/(root)/page.tsx
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/api/places/route.ts
  src/components/features/home/LatestPlaceContentSection/LatestPlaceContent.tsx
  src/components/features/home/LatestPlaceContentSection/LatestPlaceContentSection.tsx
  src/components/features/log/register/TitledInput.tsx
  src/constants/fetchConfig.ts
  src/hooks/queries/place/usePlaces.ts
  src/hooks/queries/place/usePlacesBookmark.ts
  src/types/api/place.d.ts
Labels: 🚀 배포, 🎨 디자인 / UI 작업, ✨기능 추가

#99 로그 등록/수정 시 최신 장소 미반영 문제 해결 및 캐시 전략 정비
  prisma/prisma.ts
  src/app/[locale]/(root)/auth/callback/auth.ts
  src/app/[locale]/(root)/log/[logId]/not-found.tsx
  src/app/[locale]/(root)/profile/[userId]/not-found.tsx
  src/app/actions/log-register.ts
  src/app/actions/log-update.ts
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/actions/tags.ts
  src/app/actions/user.ts
  src/app/api/follow/route.ts
  src/app/api/followers/route.ts
  src/app/api/followings/route.ts
  src/app/api/log/bookmark/check/route.ts
  src/app/api/logs/bookmark/route.ts
  src/app/api/logs/route.ts
  src/app/api/logs/search/route.ts
  src/app/api/place/bookmark/check/route.ts
  src/app/api/places/bookmark/route.ts
  src/app/api/places/route.ts
  src/app/api/public-user/route.ts
  src/components/common/ErrorTemplate.tsx
  src/hooks/mutations/log/useLogCreateMutation.ts
  src/hooks/mutations/log/useLogDeleteMutation.ts
  src/hooks/mutations/log/useLogEditMutation.ts
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#100 최신 장소 반영 오류 수정 및 캐시 전략 개선
  prisma/prisma.ts
  src/app/[locale]/(root)/auth/callback/auth.ts
  src/app/[locale]/(root)/log/[logId]/not-found.tsx
  src/app/[locale]/(root)/profile/[userId]/not-found.tsx
  src/app/actions/log-register.ts
  src/app/actions/log-update.ts
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/actions/tags.ts
  src/app/actions/user.ts
  src/app/api/follow/route.ts
  src/app/api/followers/route.ts
  src/app/api/followings/route.ts
  src/app/api/log/bookmark/check/route.ts
  src/app/api/logs/bookmark/route.ts
  src/app/api/logs/route.ts
  src/app/api/logs/search/route.ts
  src/app/api/place/bookmark/check/route.ts
  src/app/api/places/bookmark/route.ts
  src/app/api/places/route.ts
  src/app/api/public-user/route.ts
  src/components/common/ErrorTemplate.tsx
  src/hooks/mutations/log/useLogCreateMutation.ts
  src/hooks/mutations/log/useLogDeleteMutation.ts
  src/hooks/mutations/log/useLogEditMutation.ts
Labels: 🐞 버그 수정, 🚀 배포, 🛠️ 리팩토링
