Repository project2025-a/project2025-next, pull requests merged in 2025-06, with the labels that each got.

#21 모바일 ui 수정
  public/favicons/android-icon-192x192.png
  public/favicons/apple-icon-180x180.png
  public/favicons/favicon.ico
  public/favicons/ms-icon-144x144.png
  src/app/layout.tsx
  src/components/common/Button/BackButton.tsx
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Button/FollowingButton.tsx
  src/components/common/Header/Header/Header.tsx
  src/components/common/Header/Header/components/LoginStatusButtons.tsx
  src/components/common/Icons/index.tsx
  src/components/common/Modal/ModalContent.tsx
  src/components/common/SectionBlock/SectionTitle.tsx
  src/components/common/SectionBlock/TitledSection.tsx
  src/components/features/detail-log/ExtraActionButton.tsx
  src/components/features/detail-log/LogProfile.tsx
  src/components/features/home/CarouselSection/CarouselContent.tsx
  src/components/features/home/CarouselSection/CarouselSkeleton.tsx
  src/components/features/home/CitySearchForm/CitySearchForm.tsx
  src/components/features/home/InfoBanner/InfoBanner.tsx
  src/components/features/home/InfoBanner/InfoBanners.tsx
  src/components/features/home/InfoBanner/TypingText.tsx
  src/components/features/log/edit/EditMultiImageForm.tsx
  src/components/features/log/register/MultiImageForm.tsx
  src/components/features/profile/ProfileTabContent/components/ProfileTabs/TabButton.tsx
  src/hooks/queries/log/useLogBookmarkCheck.ts
Labels: 🎨 디자인 / UI 작업

#24 회의에서 나온 수정사항 개선
  public/icons/globe-black.svg
  public/icons/search-black.svg
  public/icons/user-black.svg
  src/app/(root)/log/[logId]/@placeCollect/(.)placeCollect/page.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Card/PostCard/PostCard.tsx
  src/components/common/Card/PostCard/PostCardImage.tsx
  src/components/common/Header/Header/Header.tsx
  src/components/common/Header/Header/components/SearchBarButton.tsx
  src/components/common/Header/Header/components/UserProfileButton/UserProfileButton.tsx
  src/components/common/Icons/index.tsx
  src/components/features/detail-log/LogThubmnail.tsx
  src/components/features/detail-log/PlaceImageSlider.tsx
  src/components/features/home/Hero.tsx
  src/components/features/home/HeroCategoryList.tsx
  src/components/features/home/LatestLogConentSection/LatestLogConent.tsx
  src/components/features/log/register/PlaceForm.tsx
  src/components/features/log/register/tags/TagGroup.tsx
  src/components/ui/dialog.tsx
  src/constants/cityData.ts
  src/constants/tagData.ts
  src/hooks/queries/log/useLogBookmarkCheck.ts
  src/hooks/queries/place/useIsPlaceBookmarkCheck.ts
Labels: 🎨 디자인 / UI 작업

#26 요청 수정사항 반영(유저 삭제 기능 및 프로필 페이지 UX/UI 전반 개선)
  prisma/schema.prisma
  src/app/(root)/profile/[userId]/page.tsx
  src/app/(root)/profile/editor/page.tsx
  src/app/actions/storage.ts
  src/app/actions/user.ts
  src/app/api/user/route.ts
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Button/FollowingButton.tsx
  src/components/common/Button/LogoutButton.tsx
  src/components/common/Header/Header/components/LoginStatusButtons.tsx
  src/components/common/Icons/index.tsx
  src/components/common/UserImage.tsx
  src/components/features/home/CitySearchForm/CitySearchForm.tsx
  src/components/features/home/CitySearchForm/SearchDropBox/components/CitySearchDropbox.tsx
  src/components/features/login/SocialLoginButtons.tsx
  src/components/features/profile-editor/AccountDeleteSection/AccountDeleteButton.tsx
  src/components/features/profile-editor/AccountDeleteSection/AccountDeleteDialog.tsx
  src/components/features/profile-editor/AvatarEditSection.tsx
  src/components/features/profile/ProfileHeader/ProfileHeader.tsx
  src/constants/errorMessages.ts
  src/hooks/useQueryPagination.ts
  src/lib/utils.ts
  src/stores/searchStore.ts
  src/utils/buildPublicUrl.ts
Labels: 🐞 버그 수정, 🛠️ 리팩토링, 🎨 디자인 / UI 작업

#28 캐시 무효화를 위한 글로벌 태그 전략 적용 및 hydration mismatch 대응
  src/app/actions/keys.ts
  src/app/actions/log-update.ts
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/actions/tags.ts
  src/app/actions/user.ts
  src/components/features/profile/ProfileTabContent/components/ProfileContent/components/MyLogs.tsx
  src/components/features/profile/ProfileTabContent/components/ProfileContent/components/SaveLogs.tsx
  src/components/features/profile/ProfileTabContent/components/ProfileContent/components/SavePlaces.tsx
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#30 빌드 실패 수정
  src/app/(root)/profile/editor/page.tsx
  src/app/actions/log-update.ts
Labels: 🚀 배포

#31 presignedUrl 방식 적용, ui 수정
  src/app/(root)/log/[logId]/page.tsx
  src/app/(write)/[logId]/edit/page.tsx
  src/app/(write)/register/log/page.tsx
  src/app/actions/log-register.ts
  src/app/actions/storage.ts
  src/components/common/Button/BackButton.tsx
  src/components/common/Header/Header2.tsx
  src/components/features/detail-log/PlaceImageSlider.tsx
  src/hooks/mutations/log/useLogCreateMutation.ts
Labels: 🛠️ 리팩토링, 🎨 디자인 / UI 작업

#35 약관 및 정책 페이지 추가 및 공지사항 초기화
  src/app/(no-header-footer)/notice/page.tsx
  src/app/(no-header-footer)/privacy/page.tsx
  src/app/(no-header-footer)/terms/page.tsx
  src/components/common/Header/Header/components/UserProfileButton/UserProfileButton.tsx
  src/constants/pathname.ts
Labels: 🎨 디자인 / UI 작업

#36 정책 페이지 추가 및 UI 문구/스타일 수정, 인스타 링크 제거
  prisma/schema.prisma
  src/app/(no-header-footer)/notice/page.tsx
  src/app/(no-header-footer)/privacy/page.tsx
  src/app/(no-header-footer)/terms/page.tsx
  src/app/(write)/register/tags/city/page.tsx
  src/app/(write)/register/tags/country/page.tsx
  src/app/(write)/register/tags/mood/page.tsx
  src/app/(write)/register/tags/sigungu/page.tsx
  src/components/common/Footer/ContactLink.tsx
  src/components/common/Header/Header/components/UserProfileButton/UserProfileButton.tsx
  src/components/common/Header/LogEditHeader.tsx
  src/components/features/home/InfoBanner/InfoBanners.tsx
  src/components/features/home/LatestLogConentSection/LatestLogConent.tsx
  src/components/features/log/edit/ConfirmDeleteDialog.tsx
  src/components/features/log/register/tags/PageIntro.tsx
  src/constants/pathname.ts
Labels: 🚀 배포

#37 이용약관 및 개인정보처리방침 페이지 내 특수문자 이스케이프 처리
  src/app/(no-header-footer)/privacy/page.tsx
  src/app/(no-header-footer)/terms/page.tsx
Labels: 🚀 배포

#40 Develop
  src/app/(root)/profile/editor/page.tsx
  src/app/(write)/register/log/page.tsx
  src/app/actions/log-register.ts
  src/app/actions/log-update.ts
  src/app/actions/log.ts
  src/app/actions/storage.ts
  src/components/features/log/register/MultiImageForm.tsx
  src/hooks/mutations/log/useLogCreateMutation.ts
  src/hooks/useMultipleImagePreview.ts
  src/utils/buildPublicUrl.ts
  src/utils/getStorageImage.ts
  src/utils/upload.ts
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#41 ui 수정
  src/app/(write)/register/log/page.tsx
  src/app/(write)/register/tags/city/page.tsx
  src/app/(write)/register/tags/sigungu/page.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Header/Header3.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/detail-log/PlaceImageSlider.tsx
  src/components/features/log/register/tags/PageIntro.tsx
  src/components/features/log/register/tags/TagGroup.tsx
  src/components/features/log/register/tags/constant.ts
  src/constants/cityData.ts
Labels: 🎨 디자인 / UI 작업

#44 캐시 문제 대응 위해 log에 작성자 정보 포함
  src/app/(root)/log/[logId]/page.tsx
  src/app/actions/log.ts
  src/components/features/detail-log/LogAuthorIntro.tsx
  src/components/features/detail-log/SimpleUserProfile.tsx
  src/types/api/log.d.ts
Labels: 🐞 버그 수정, 🚀 배포

#48 404 처리 개선 및 드롭다운 동작 개선 배포
  src/app/(root)/log/[logId]/not-found.tsx
  src/app/(root)/log/[logId]/page.tsx
  src/app/(root)/profile/[userId]/not-found.tsx
  src/app/(root)/profile/[userId]/page.tsx
  src/app/actions/log.ts
  src/components/common/ErrorTemplate.tsx
  src/components/common/Header/Header/components/UserProfileButton/UserProfileButton.tsx
  src/components/common/Header/Header/components/UserProfileButton/components/MyProfileButton.tsx
Labels: 🚀 배포

#50 404 화면 선명도 개선 및 로그인 모달 레이아웃
  public/icons/map.svg
  public/images/404.png
  src/components/common/ErrorTemplate.tsx
  src/components/common/Icons/index.tsx
  src/components/common/Modal/ModalContent.tsx
Labels: 🎨 디자인 / UI 작업

#52 상세 페이지 북마크 수 UI 개선 및 낙관적 업데이트 구현
  src/app/(root)/log/[logId]/page.tsx
  src/app/actions/log.ts
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Header/Header/Header.tsx
  src/components/features/detail-log/LogBookmarkWithCount.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/home/CarouselSection/Carousel.tsx
  src/components/features/profile/ProfileHeader/ProfileHeader.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/hooks/mutations/place/usePlaceBookmarkMutation.ts
  src/lib/utils.ts
  src/types/api/log.d.ts
Labels: 🎨 디자인 / UI 작업, ✨기능 추가

#57 로그인 모달 및 UI 요소 스타일 조정
  public/icons/bookmark.svg
  src/app/(root)/@modal/(.)login/page.tsx
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Button/XButton.tsx
  src/components/common/Icons/index.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/home/CitySearchForm/CitySearchForm.tsx
  src/components/features/home/CitySearchForm/SearchDropBox/SearchDropBox.tsx
Labels: 🎨 디자인 / UI 작업

#58 6/19일 수정 배포
  public/icons/bookmark.svg
  src/app/(root)/@modal/(.)login/page.tsx
  src/app/(root)/log/[logId]/page.tsx
  src/app/(write)/register/log/page.tsx
  src/components/common/Button/Bookmark/LogBookMarkButton.tsx
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Button/XButton.tsx
  src/components/common/Icons/index.tsx
  src/components/features/detail-log/LogAuthorIntro.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/detail-log/LogThubmnail.tsx
  src/components/features/detail-log/TagRow.tsx
  src/components/features/home/CitySearchForm/CitySearchForm.tsx
  src/components/features/home/CitySearchForm/SearchDropBox/SearchDropBox.tsx
  src/components/features/log/register/PlaceForm.tsx
  src/components/features/log/register/TextForm.tsx
  src/components/ui/button.tsx
Labels: 🚀 배포, 🎨 디자인 / UI 작업

#62 ui 수정, 로그 등록 기능 추가 및 개선
  src/app/(write)/register/layout.tsx
  src/app/(write)/register/log/page.tsx
  src/components/common/Header/Header3.tsx
  src/components/features/detail-log/LogThumbnail.tsx
  src/components/features/detail-log/PlaceImageSlider.tsx
  src/components/features/log/register/MultiImageForm.tsx
  src/components/features/log/register/tags/SingleTagGroup.tsx
  src/components/features/profile-editor/AvatarEditSection.tsx
  src/hooks/useMultipleImagePreview.ts
  src/lib/zod/logSchema.ts
  src/stores/logCreationStore.ts
  src/utils/compressImageToWebp.ts
  src/utils/upload.ts
Labels: 🐞 버그 수정, 🎨 디자인 / UI 작업, ✨기능 추가

#66 개인정보처리방침, 이용약관, 공지사항 페이지 다국어 지원 기능 추가
  messages/en.json
  messages/ko.json
  src/app/[locale]/(no-header-footer)/notice/page.tsx
  src/app/[locale]/(no-header-footer)/privacy/page.tsx
  src/app/[locale]/(no-header-footer)/terms/page.tsx
  src/components/features/privacy/PrivacyArticleSection.tsx
  src/components/features/terms/TermsArticleSection.tsx
Labels: 🚀 배포

#71 리팩토링 및 기능 추가
  src/app/[locale]/(root)/page.tsx
  src/app/[locale]/(write)/[logId]/edit/_EditPage/page.tsx
  src/app/actions/keys.ts
  src/app/actions/log-update.ts
  src/app/actions/log.ts
  src/app/actions/place.ts
  src/app/actions/tags.ts
  src/app/actions/user.ts
  src/components/features/detail-log/LogThumbnail.tsx
  src/components/features/home/LatestLogContentSection/LatestLogContent.tsx
  src/components/features/home/LatestLogContentSection/LatestLogContentSection.tsx
  src/components/features/log/edit/EditMultiImageForm.tsx
  src/components/features/log/register/MultiImageForm.tsx
  src/components/features/log/register/ReorderItem.tsx
  src/hooks/queries/log/useLogs.ts
  src/hooks/queries/log/useLogsBookmark.ts
  src/types/api/log.d.ts
Labels: 🛠️ 리팩토링, 🎨 디자인 / UI 작업, ✨기능 추가

#74 SSR 캐시 무효화 미적용으로 인한 북마크 반영 오류 수정
  src/app/actions/log.ts
  src/app/api/log/bookmark/check/route.ts
Labels: 🐞 버그 수정, 🚀 배포

#76 장소 북마크 캐시 및 UI 동기화 개선, hydration 오류 대응
  src/app/[locale]/(root)/log/[logId]/page.tsx
  src/app/api/place/bookmark/check/route.ts
  src/components/common/Button/Bookmark/PlaceBookMarkButton.tsx
  src/components/common/Header/Header/components/UserProfileButton/UserProfileButton.tsx
  src/components/common/Header/LogEditHeader.tsx
  src/components/features/detail-log/LogContent.tsx
  src/components/features/detail-log/LogContentSection.tsx
  src/components/features/home/InfoBanner/InfoBanners.tsx
  src/components/features/home/InfoBanner/RegisterLinkButtons.tsx
  src/components/features/log/common/PlaceForm.tsx
  src/hooks/mutations/log/useLogDeleteMutation.ts
  src/hooks/mutations/place/usePlaceBookmarkMutation.ts
Labels: 🐞 버그 수정, 🚀 배포

#77 비로그인 사용자의 보호 페이지 접근 시 /login으로 리디렉션
  src/middleware.ts
Labels: 🚀 배포

#78 NotFound 페이지 다국어 처리 및 장소 카테고리 번역 버그 수정
  messages/en.json
  messages/ko.json
  src/app/[locale]/(root)/log/[logId]/not-found.tsx
  src/app/[locale]/(root)/profile/[userId]/not-found.tsx
  src/components/common/ErrorTemplate.tsx
Labels: 🐞 버그 수정, 🚀 배포, ✨기능 추가

#79 next-intl Link 컴포넌트 분리 및 레이아웃 시프트 방지 리팩토링
  src/app/[locale]/(root)/@modal/(.)login/page.tsx
  src/app/[locale]/(root)/log/[logId]/page.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/FooterPolicyLinks.tsx
  src/components/common/Header/Header/HomeLinkButton.tsx
  src/components/common/Header/Header2.tsx
  src/components/features/detail-log/LogDetailActions.tsx
  src/components/features/detail-log/LogProfile.tsx
  src/components/features/detail-log/LogProfileLink.tsx
  src/components/features/login/LoginAgreementNotice.tsx
Labels: 🐞 버그 수정, 🚀 배포, 🛠️ 리팩토링
